export const GET_ALLPRODUCTS = "GET_ALLPRODUCTS";
export const GET_ALLPRODUCTS_SUCCESS = "GET_ALLPRODUCTS_SUCCESS";
export const GET_ALLPRODUCTS_FAIL = "GET_ALLPRODUCTS_FAIL";

export const CLEAR_ERRORS='CLEAR_ERRORS'



export const GET_ALLPRODUCTSDETAILS = "GET_ALLPRODUCTSDETAILS";
export const GET_ALLPRODUCTSDETAILS_SUCCESS = "GET_ALLPRODUCTSDETAILS_SUCCESS";
export const GET_ALLPRODUCTSDETAILS_FAIL = "GET_ALLPRODUCTSDETAILS_FAIL";